using System.Linq;
using Microsoft.CodeAnalysis;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// Generates typed-ID extension methods for <see cref="IActorBus"/> for actors 
/// whose primary constructor accepts a non-string typed identifier.
/// <list type="bullet">
/// <item>For <b>user-defined</b> ID types (StructId, StronglyTypedId, or any user type 
/// implementing <c>IParsable&lt;T&gt;</c>): overloads accept the ID type directly.</item>
/// <item>For <b>primitive</b> ID types (<c>long</c>, <c>Guid</c>, etc.): overloads accept 
/// the generated nested <c>{Actor}.{Actor}Id</c> wrapper (emitted by 
/// <see cref="ActorPrimitiveIdGenerator"/>), never the raw primitive.</item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorIdBusOverloadGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actors = context.CompilationProvider
            .SelectMany((x, _) => x.Assembly.GetAllTypes().OfType<INamedTypeSymbol>())
            .Where(t => t.IsActor());

        var parsable = context.CompilationProvider
            .Select((c, _) => c.GetTypeByMetadataName("System.IParsable`1"));

        context.RegisterSourceOutput(actors.Combine(parsable), (ctx, item) =>
        {
            var (actor, iParsable) = item;

            // Determine what ID type the actor uses and how to generate overloads
            var idInfo = GetActorIdInfo(actor, iParsable);
            if (idInfo is null)
                return;

            var (busIdTypeName, idInterpolation) = idInfo.Value;
            var grainType = actor.Name.ToLowerInvariant();
            var file = $"{actor.ToFileName()}.IdBus.g.cs";

            ctx.AddSource(file,
                $$"""
                // <auto-generated/>
                using System.Threading.Tasks;
                using Devlooped.CloudActors;
                                
                static partial class ActorBusExtensions
                {
                    /// <summary>
                    /// Invokes a state-changing command on a <see cref="{{actor.ToDisplayString(FullName)}}"/> actor.
                    /// </summary>
                    public static Task ExecuteAsync(this IActorBus bus, {{busIdTypeName}} id, IActorCommand command)
                        => bus.ExecuteAsync($"{{grainType}}/{{idInterpolation}}", command);
                
                    /// <summary>
                    /// Invokes a state-changing command on a <see cref="{{actor.ToDisplayString(FullName)}}"/> actor.
                    /// </summary>
                    public static Task<TResult> ExecuteAsync<TResult>(this IActorBus bus, {{busIdTypeName}} id, IActorCommand<TResult> command)
                        => bus.ExecuteAsync<TResult>($"{{grainType}}/{{idInterpolation}}", command);
                
                    /// <summary>
                    /// Invokes a read-only query on a <see cref="{{actor.ToDisplayString(FullName)}}"/> actor.
                    /// </summary>
                    public static Task<TResult> QueryAsync<TResult>(this IActorBus bus, {{busIdTypeName}} id, IActorQuery<TResult> query)
                        => bus.QueryAsync<TResult>($"{{grainType}}/{{idInterpolation}}", query);
                }
                """);
        });
    }

    /// <summary>
    /// Returns the bus parameter type name and the interpolation expression for the ID.
    /// For primitive IDs: (<c>Actor.ActorId</c>, <c>{id.Id}</c>).
    /// For user-defined IDs: (<c>UserDefinedId</c>, <c>{id}</c>).
    /// Returns <c>null</c> for string or unrecognized ID types.
    /// </summary>
    static (string BusIdTypeName, string IdInterpolation)? GetActorIdInfo(INamedTypeSymbol actor, INamedTypeSymbol? iParsable)
    {
        var ctor = actor.Constructors
            .Where(c => !c.IsStatic && c.Parameters.Length > 0)
            .OrderBy(c => c.Parameters.Length)
            .FirstOrDefault();

        if (ctor is null)
            return null;

        var idType = ctor.Parameters[0].Type;

        if (idType.SpecialType == SpecialType.System_String)
            return null;

        // Primitive types get a generated nested wrapper: {Actor}.{Actor}Id
        if (ActorPrimitiveIdGenerator.IsPrimitiveType(idType))
        {
            var wrapperTypeName = $"{actor.ToDisplayString(FullName)}.{actor.Name}Id";
            return (wrapperTypeName, "{id.Id}");
        }

        // User-defined typed IDs: StructId or IParsable<T> implementations
        if (iParsable is not null)
        {
            var implementsParsable = idType.AllInterfaces.Any(i =>
                i.IsGenericType &&
                i.ConstructedFrom.Equals(iParsable, SymbolEqualityComparer.Default));

            if (implementsParsable)
                return (idType.ToDisplayString(FullName), "{id}");
        }

        var isStructId = idType.AllInterfaces.Any(i =>
            i.ContainingNamespace?.Name == "StructId" &&
            i.Name == "IStructId");

        if (isStructId)
            return (idType.ToDisplayString(FullName), "{id}");

        return null;
    }
}
