using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// Generates typed-ID extension methods for <see cref="IActorBus"/> for actors 
/// whose primary constructor accepts a non-string typed identifier.
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorIdBusOverloadGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actors = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is ClassDeclarationSyntax cds &&
                cds.AttributeLists.Count > 0,
            transform: static (ctx, ct) =>
            {
                if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol symbol)
                    return (ActorIdBusOverloadModel?)null;

                if (!symbol.IsActor())
                    return null;

                var iParsable = ctx.SemanticModel.Compilation.GetTypeByMetadataName("System.IParsable`1");
                var guidType = ctx.SemanticModel.Compilation.GetTypeByMetadataName("System.Guid");
                var hasCreateVersion7 = guidType?.GetMembers("CreateVersion7")
                    .OfType<IMethodSymbol>()
                    .Any(m => m.IsStatic && m.Parameters.Length == 0) == true;

                var model = ModelExtractors.ExtractActorModel(symbol, iParsable, hasCreateVersion7);
                if (model is null)
                    return null;

                var actor = model.Value;
                // Skip actors with no typed ID
                if (actor.IdTypeFullName is null)
                    return null;

                // Determine bus parameter type and interpolation
                if (actor.IsPrimitiveId)
                {
                    var wrapperTypeName = $"{actor.FullName}.{actor.Name}Id";
                    return new ActorIdBusOverloadModel(actor.Name, actor.FullName, wrapperTypeName, "{id.Id}");
                }
                else if (actor.IsTypedId)
                {
                    return new ActorIdBusOverloadModel(actor.Name, actor.FullName, actor.IdTypeFullName, "{id}");
                }

                return null;
            })
            .Where(static x => x != null)
            .Select(static (x, _) => x!.Value)
            .WithTrackingName(TrackingNames.ActorIdOverloads);

        context.RegisterSourceOutput(actors, (ctx, model) =>
        {
            var grainType = model.ActorName.ToLowerInvariant();
            var file = $"{model.ActorFullName.Replace('+', '.')}.IdBus.g.cs";

            ctx.AddSource(file,
                $$"""
                // <auto-generated/>
                using System.Threading.Tasks;
                using Devlooped.CloudActors;
                                
                static partial class ActorBusExtensions
                {
                    /// <summary>
                    /// Invokes a state-changing command on a <see cref="{{model.ActorFullName}}"/> actor.
                    /// </summary>
                    public static Task ExecuteAsync(this IActorBus bus, {{model.BusIdTypeName}} id, IActorCommand command)
                        => bus.ExecuteAsync($"{{grainType}}/{{model.IdInterpolation}}", command);
                
                    /// <summary>
                    /// Invokes a state-changing command on a <see cref="{{model.ActorFullName}}"/> actor.
                    /// </summary>
                    public static Task<TResult> ExecuteAsync<TResult>(this IActorBus bus, {{model.BusIdTypeName}} id, IActorCommand<TResult> command)
                        => bus.ExecuteAsync<TResult>($"{{grainType}}/{{model.IdInterpolation}}", command);
                
                    /// <summary>
                    /// Invokes a read-only query on a <see cref="{{model.ActorFullName}}"/> actor.
                    /// </summary>
                    public static Task<TResult> QueryAsync<TResult>(this IActorBus bus, {{model.BusIdTypeName}} id, IActorQuery<TResult> query)
                        => bus.QueryAsync<TResult>($"{{grainType}}/{{model.IdInterpolation}}", query);
                }
                """);
        });
    }
}
