using System.Linq;
using Microsoft.CodeAnalysis;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// Generates typed-ID extension methods for <see cref="IActorBus"/> for actors 
/// whose primary constructor accepts a non-string <c>IParsable&lt;T&gt;</c> identifier 
/// (such as StructId types). For each such actor, three overloads are emitted: 
/// void command, typed command, and query, all formatting the grain ID as 
/// <c>$"{grainType}/{id}"</c>.
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorIdBusOverloadGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actors = context.CompilationProvider
            .SelectMany((x, _) => x.Assembly.GetAllTypes().OfType<INamedTypeSymbol>())
            .Where(t => t.IsActor());

        var parsable = context.CompilationProvider
            .Select((c, _) => c.GetTypeByMetadataName("System.IParsable`1"));

        context.RegisterSourceOutput(actors.Combine(parsable), (ctx, item) =>
        {
            var (actor, iParsable) = item;
            if (iParsable is null)
                return;

            var idType = GetTypedIdType(actor, iParsable);
            if (idType is null)
                return;

            var idTypeName = idType.ToDisplayString(FullName);
            var grainType = actor.Name.ToLowerInvariant();
            var file = $"{actor.ToFileName()}.IdBus.g.cs";

            ctx.AddSource(file,
                $$"""
                // <auto-generated/>
                using System.Threading.Tasks;
                using Devlooped.CloudActors;
                                
                static partial class ActorBusExtensions
                {
                    /// <summary>
                    /// Invokes a state-changing command on a <see cref="{{actor.ToDisplayString(FullName)}}"/> actor.
                    /// </summary>
                    public static Task ExecuteAsync(this IActorBus bus, {{idTypeName}} id, IActorCommand command)
                        => bus.ExecuteAsync($"{{grainType}}/{id}", command);
                
                    /// <summary>
                    /// Invokes a state-changing command on a <see cref="{{actor.ToDisplayString(FullName)}}"/> actor.
                    /// </summary>
                    public static Task<TResult> ExecuteAsync<TResult>(this IActorBus bus, {{idTypeName}} id, IActorCommand<TResult> command)
                        => bus.ExecuteAsync<TResult>($"{{grainType}}/{id}", command);
                
                    /// <summary>
                    /// Invokes a read-only query on a <see cref="{{actor.ToDisplayString(FullName)}}"/> actor.
                    /// </summary>
                    public static Task<TResult> QueryAsync<TResult>(this IActorBus bus, {{idTypeName}} id, IActorQuery<TResult> query)
                        => bus.QueryAsync<TResult>($"{{grainType}}/{id}", query);
                }
                """);
        });
    }

    static ITypeSymbol? GetTypedIdType(INamedTypeSymbol actor, INamedTypeSymbol iParsable)
    {
        var ctor = actor.Constructors
            .Where(c => !c.IsStatic && c.Parameters.Length > 0)
            .OrderBy(c => c.Parameters.Length)
            .FirstOrDefault();

        if (ctor is null)
            return null;

        var idType = ctor.Parameters[0].Type;

        // String constructors are handled by existing overloads
        if (idType.SpecialType == SpecialType.System_String)
            return null;

        // Check if idType implements IParsable<T> directly
        var implementsParsable = idType.AllInterfaces.Any(i =>
            i.IsGenericType &&
            i.ConstructedFrom.Equals(iParsable, SymbolEqualityComparer.Default));

        if (implementsParsable)
            return idType;

        // StructId types implement IParsable<T> via a separate generator that runs
        // in parallel, so we can't see it. Detect IStructId/IStructId<T> by name instead.
        var isStructId = idType.AllInterfaces.Any(i =>
            i.ContainingNamespace?.Name == "StructId" &&
            (i.Name == "IStructId"));

        return isStructId ? idType : null;
    }
}
