using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// For actors whose primary constructor first parameter is a primitive type 
/// (e.g. <c>long</c>, <c>Guid</c>), generates a nested strongly-typed ID wrapper 
/// and a <c>NewId</c> factory method. This enables type-safe bus overloads per actor 
/// without collisions when multiple actors share the same primitive ID type.
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorPrimitiveIdGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actors = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is ClassDeclarationSyntax cds &&
                cds.AttributeLists.Count > 0,
            transform: static (ctx, ct) =>
            {
                if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol symbol)
                    return null;

                if (!symbol.IsActor())
                    return null;

                var iParsable = ctx.SemanticModel.Compilation.GetTypeByMetadataName("System.IParsable`1");
                var guidType = ctx.SemanticModel.Compilation.GetTypeByMetadataName("System.Guid");
                var hasCreateVersion7 = guidType?.GetMembers("CreateVersion7")
                    .OfType<IMethodSymbol>()
                    .Any(m => m.IsStatic && m.Parameters.Length == 0) == true;

                return ModelExtractors.ExtractActorModel(symbol, iParsable, hasCreateVersion7);
            })
            .Where(static x => x != null && x.Value.IsPrimitiveId)
            .Select(static (x, _) => x!.Value)
            .WithTrackingName(TrackingNames.PrimitiveIdModels);

        context.RegisterSourceOutput(actors, (ctx, actor) =>
        {
            var idTypeName = actor.IdTypeFullName!;
            var ns = actor.Namespace;
            var file = $"{actor.FileName}.PrimitiveId.g.cs";
            var nsOpen = $"namespace {ns};\n\n";

            var parameterlessNewId = "";
            if (idTypeName == "System.Guid")
            {
                var guidFactory = actor.HasGuidCreateVersion7 ? "System.Guid.CreateVersion7()" : "System.Guid.NewGuid()";
                parameterlessNewId = $$"""


                    /// <summary>
                    /// Creates a new <see cref="{{actor.Name}}Id"/> with a newly generated <see cref="System.Guid"/>.
                    /// </summary>
                    public static {{actor.Name}}Id NewId() => new({{guidFactory}});
                """;
            }

            ctx.AddSource(file,
                $$"""
                // <auto-generated/>
                {{nsOpen}}partial class {{actor.Name}}
                {
                    /// <summary>
                    /// Strongly-typed identifier for <see cref="{{actor.Name}}"/> actors.
                    /// </summary>
                    public readonly record struct {{actor.Name}}Id({{idTypeName}} Id)
                    {
                        /// <inheritdoc/>
                        public override string ToString() => Id.ToString();
                    }

                    /// <summary>
                    /// Creates a new <see cref="{{actor.Name}}Id"/> from a raw <see cref="{{idTypeName}}"/> value.
                    /// </summary>
                    public static {{actor.Name}}Id NewId({{idTypeName}} id) => new(id);{{parameterlessNewId}}
                }
                """);
        });
    }

    /// <summary>
    /// A type is "primitive" if it's a well-known system value type:
    /// - Has a non-None SpecialType (int, long, short, byte, etc.), or
    /// - Is a value type in the System namespace (Guid, DateTime, TimeSpan, etc.)
    /// </summary>
    internal static bool IsPrimitiveType(ITypeSymbol type)
    {
        if (type.SpecialType != SpecialType.None)
            return true;

        if (type.IsValueType && type.ContainingNamespace?.ToDisplayString() == "System")
            return true;

        return false;
    }
}
