using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Devlooped.CloudActors;

/// <summary>
/// Generates strongly-typed, message-specific <see cref="IActorBus"/> extension methods for each actor.
/// For actors with a typed ID, emits (TypedId, ConcreteMessage) overloads.
/// For actors with a string ID, emits (string, ConcreteMessage) overloads.
/// Only messages actually handled by the actor (declared handler methods) get overloads.
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorBusOverloadGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actors = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is ClassDeclarationSyntax cds &&
                cds.AttributeLists.Count > 0,
            transform: static (ctx, ct) =>
            {
                if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol symbol)
                    return (ActorModel?)null;

                if (!symbol.IsActor())
                    return null;

                var iParsable = ctx.SemanticModel.Compilation.GetTypeByMetadataName("System.IParsable`1");
                var guidType = ctx.SemanticModel.Compilation.GetTypeByMetadataName("System.Guid");
                var hasCreateVersion7 = guidType?.GetMembers("CreateVersion7")
                    .OfType<IMethodSymbol>()
                    .Any(m => m.IsStatic && m.Parameters.Length == 0) == true;

                return ModelExtractors.ExtractActorModel(symbol, iParsable, hasCreateVersion7);
            })
            .Where(static x => x != null)
            .Select(static (x, _) => x!.Value)
            .WithTrackingName(TrackingNames.BusOverloads);

        // Emit the base partial class only when at least one actor has emittable overloads.
        // Using Collect+Select(bool) keeps this a single cached bool — not per-actor — so the
        // base file is only added/removed when the set of emittable actors crosses zero.
        var hasOverloads = actors
            .Where(static a =>
                (a.VoidCommands.Length > 0 || a.Commands.Length > 0 || a.Queries.Length > 0) &&
                (a.IsPrimitiveId || a.IsTypedId))
            .Collect()
            .Select(static (arr, _) => arr.Length > 0);

        context.RegisterSourceOutput(hasOverloads, static (ctx, hasAny) =>
        {
            if (!hasAny)
                return;

            ctx.AddSource("ActorBusExtensions.g.cs",
                """
                // <auto-generated/>
                using System.ComponentModel;
                [EditorBrowsable(EditorBrowsableState.Never)]
                public static partial class ActorBusExtensions { }
                """);
        });

        // Per-actor overloads remain incremental: each actor's file is independently cached.
        context.RegisterSourceOutput(actors, (ctx, actor) =>
        {
            if (actor.VoidCommands.Length == 0 && actor.Commands.Length == 0 && actor.Queries.Length == 0)
                return;

            var grainType = actor.Name.ToLowerInvariant();

            string busIdTypeName;
            string idExpr;

            if (actor.IsPrimitiveId)
            {
                busIdTypeName = $"{actor.FullName}.{actor.Name}Id";
                idExpr = $"$\"{grainType}/{{id.Id}}\"";
            }
            else if (actor.IsTypedId && actor.IdTypeFullName != null)
            {
                busIdTypeName = actor.IdTypeFullName;
                idExpr = $"$\"{grainType}/{{id}}\"";
            }
            else
            {
                // Actor with no recognized ID type — no typed overloads can be generated.
                return;
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("#nullable enable");
            sb.AppendLine("using System.Runtime.CompilerServices;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine("using Devlooped.CloudActors;");
            sb.AppendLine();
            sb.AppendLine("static partial class ActorBusExtensions");
            sb.AppendLine("{");

            foreach (var cmd in actor.VoidCommands.AsImmutableArray())
            {
                sb.AppendLine(
                    $"    /// <summary>Invokes a state-changing command on a <see cref=\"{actor.FullName}\"/> actor.</summary>");
                sb.AppendLine(
                    $"    public static Task ExecuteAsync(this IActorBus bus, {busIdTypeName} id, {cmd.Type} command,");
                sb.AppendLine(
                    $"        [CallerMemberName] string? callerName = default, [CallerFilePath] string? callerFile = default, [CallerLineNumber] int? callerLine = default)");
                sb.AppendLine(
                    $"        => bus.ExecuteAsync({idExpr}, (IActorCommand)command, callerName, callerFile, callerLine);");
                sb.AppendLine();
            }

            foreach (var cmd in actor.Commands.AsImmutableArray())
            {
                var returnType = cmd.ReturnTypeFullName!;
                sb.AppendLine(
                    $"    /// <summary>Invokes a state-changing command on a <see cref=\"{actor.FullName}\"/> actor.</summary>");
                sb.AppendLine(
                    $"    public static Task<{returnType}> ExecuteAsync(this IActorBus bus, {busIdTypeName} id, {cmd.Type} command,");
                sb.AppendLine(
                    $"        [CallerMemberName] string? callerName = default, [CallerFilePath] string? callerFile = default, [CallerLineNumber] int? callerLine = default)");
                sb.AppendLine(
                    $"        => bus.ExecuteAsync<{returnType}>({idExpr}, command, callerName, callerFile, callerLine);");
                sb.AppendLine();
            }

            foreach (var query in actor.Queries.AsImmutableArray())
            {
                var returnType = query.ReturnTypeFullName!;
                sb.AppendLine(
                    $"    /// <summary>Invokes a read-only query on a <see cref=\"{actor.FullName}\"/> actor.</summary>");
                sb.AppendLine(
                    $"    public static Task<{returnType}> QueryAsync(this IActorBus bus, {busIdTypeName} id, {query.Type} query,");
                sb.AppendLine(
                    $"        [CallerMemberName] string? callerName = default, [CallerFilePath] string? callerFile = default, [CallerLineNumber] int? callerLine = default)");
                sb.AppendLine(
                    $"        => bus.QueryAsync<{returnType}>({idExpr}, query, callerName, callerFile, callerLine);");
                sb.AppendLine();
            }

            sb.AppendLine("}");

            ctx.AddSource($"{actor.FileName}.Bus.g.cs", sb.ToString());
        });
    }
}
