using System.Linq;
using Microsoft.CodeAnalysis;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// For actors whose primary constructor first parameter is a primitive type 
/// (e.g. <c>long</c>, <c>Guid</c>), generates a nested strongly-typed ID wrapper 
/// and a <c>NewId</c> factory method. This enables type-safe bus overloads per actor 
/// without collisions when multiple actors share the same primitive ID type.
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorPrimitiveIdGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var actors = context.CompilationProvider
            .SelectMany((x, _) => x.Assembly.GetAllTypes().OfType<INamedTypeSymbol>())
            .Where(t => t.IsActor());

        var actorsWithCompilation = actors.Combine(context.CompilationProvider);

        context.RegisterSourceOutput(actorsWithCompilation, (ctx, pair) =>
        {
            var (actor, compilation) = pair;
            var idType = GetPrimitiveIdType(actor);
            if (idType is null)
                return;

            var idTypeName = idType.ToDisplayString(FullName);
            var ns = actor.ContainingNamespace.IsGlobalNamespace
                ? null
                : actor.ContainingNamespace.ToDisplayString();

            var file = $"{actor.ToFileName()}.PrimitiveId.g.cs";

            var nsOpen = ns is null ? "" : $"namespace {ns};\n\n";

            // For Guid IDs, emit a parameterless NewId() that generates a new value.
            var parameterlessNewId = "";
            if (idType.ToDisplayString(FullName) == "System.Guid")
            {
                var guidType = compilation.GetTypeByMetadataName("System.Guid");
                var hasCreateVersion7 = guidType?.GetMembers("CreateVersion7")
                    .OfType<IMethodSymbol>()
                    .Any(m => m.IsStatic && m.Parameters.Length == 0) == true;

                var guidFactory = hasCreateVersion7 ? "System.Guid.CreateVersion7()" : "System.Guid.NewGuid()";

                parameterlessNewId = $$"""


                    /// <summary>
                    /// Creates a new <see cref="{{actor.Name}}Id"/> with a newly generated <see cref="System.Guid"/>.
                    /// </summary>
                    public static {{actor.Name}}Id NewId() => new({{guidFactory}});
                """;
            }

            ctx.AddSource(file,
                $$"""
                // <auto-generated/>
                {{nsOpen}}partial class {{actor.Name}}
                {
                    /// <summary>
                    /// Strongly-typed identifier for <see cref="{{actor.Name}}"/> actors.
                    /// </summary>
                    public readonly record struct {{actor.Name}}Id({{idTypeName}} Id)
                    {
                        /// <inheritdoc/>
                        public override string ToString() => Id.ToString();
                    }

                    /// <summary>
                    /// Creates a new <see cref="{{actor.Name}}Id"/> from a raw <see cref="{{idTypeName}}"/> value.
                    /// </summary>
                    public static {{actor.Name}}Id NewId({{idTypeName}} id) => new(id);{{parameterlessNewId}}
                }
                """);
        });
    }

    /// <summary>
    /// Returns the first ctor parameter's type if it is a primitive/BCL value type 
    /// (not string, not a user-defined typed ID).
    /// </summary>
    internal static ITypeSymbol? GetPrimitiveIdType(INamedTypeSymbol actor)
    {
        var ctor = actor.Constructors
            .Where(c => !c.IsStatic && c.Parameters.Length > 0)
            .OrderBy(c => c.Parameters.Length)
            .FirstOrDefault();

        if (ctor is null)
            return null;

        var idType = ctor.Parameters[0].Type;

        if (idType.SpecialType == SpecialType.System_String)
            return null;

        if (IsPrimitiveType(idType))
            return idType;

        return null;
    }

    /// <summary>
    /// A type is "primitive" if it's a well-known system value type:
    /// - Has a non-None SpecialType (int, long, short, byte, etc.), or
    /// - Is a value type in the System namespace (Guid, DateTime, TimeSpan, etc.)
    /// </summary>
    internal static bool IsPrimitiveType(ITypeSymbol type)
    {
        if (type.SpecialType != SpecialType.None)
            return true;

        if (type.IsValueType && type.ContainingNamespace?.ToDisplayString() == "System")
            return true;

        return false;
    }
}
