using Microsoft.CodeAnalysis;

namespace Devlooped.CloudActors;

[Generator(LanguageNames.CSharp)]
class CloudActorsAttributeGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
        => context.RegisterImplementationSourceOutput(context.CompilationProvider, (ctx, compilation)
            =>
            {
                ctx.AddSource($"CloudActors.cs",
                    $$"""
                    // <auto-generated/>
                    #pragma warning disable CS0436 // Type conflicts with imported type

                    [assembly: Devlooped.CloudActors]

                    namespace Devlooped
                    {
                        [System.AttributeUsage(System.AttributeTargets.Assembly)]
                        class CloudActorsAttribute : System.Attribute { } 
                    }
                    #pragma warning restore CS0436                    
                    """);
            });
}
