using System.Diagnostics;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Scriban;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

[Generator(LanguageNames.CSharp)]
class EventSourcedGenerator : IIncrementalGenerator
{
    static readonly Template template = Template.Parse(ThisAssembly.Resources.EventSourced.Text);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.GetOrleansConfig();

        var actors = context.SyntaxProvider.CreateSyntaxProvider(
            predicate: static (node, _) =>
                node is ClassDeclarationSyntax cds &&
                cds.AttributeLists.Count > 0 &&
                cds.BaseList?.Types.Count > 0,
            transform: static (ctx, ct) =>
            {
                if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol symbol)
                    return (EventSourcedModel?)null;

                if (!symbol.IsActor())
                    return null;

                if (!symbol.AllInterfaces.Any(i => i.ToDisplayString(FullName) == "Devlooped.CloudActors.IEventSourced"))
                    return null;

                // Skip if the user has already implemented any IEventSourced members
                var esInterface = ctx.SemanticModel.Compilation.GetTypeByMetadataName("Devlooped.CloudActors.IEventSourced");
                if (esInterface != null && esInterface.GetMembers()
                    .Select(m => symbol.FindImplementationForInterfaceMember(m))
                    .Any(impl => impl != null))
                    return null;

                return new EventSourcedModel(
                    Namespace: symbol.ContainingNamespace.IsGlobalNamespace ? "" : symbol.ContainingNamespace.ToDisplayString(),
                    Name: symbol.Name,
                    FullName: symbol.ToDisplayString(FullName),
                    Events: default);
            })
            .Where(static x => x != null)
            .Select(static (x, _) => x!.Value)
            .WithTrackingName(TrackingNames.EventSourcedModels);

        context.RegisterSourceOutput(
            actors.Combine(context.CompilationProvider).Combine(context.ParseOptionsProvider).Combine(config),
            (ctx, source) =>
            {
                var (((model, compilation), parseOptions), config) = source;
                var ns = model.Namespace;

                // First render with empty events to get the Raise<T>() method
                var initial = template.Render(new { model.Namespace, model.Name, Events = System.Array.Empty<string>(), Version = ThisAssembly.Info.InformationalVersion }, member => member.Name);
                compilation = compilation.AddSyntaxTrees(CSharpSyntaxTree.ParseText(initial, parseOptions as CSharpParseOptions));

                var symbol = compilation.GetTypeByMetadataName(model.FullName);
                Debug.Assert(symbol != null);

                var syntax = symbol!.DeclaringSyntaxReferences.First();
                var events = EventLocator.FindRaisedEvents(compilation, syntax.SyntaxTree);

                var eventNames = events.Select(e => e.GetTypeName(ns)).ToArray();
                var output = template.Render(new { model.Namespace, model.Name, Events = eventNames, Version = ThisAssembly.Info.InformationalVersion }, member => member.Name);

                ctx.AddSource($"{model.FullName.Replace('+', '.')}.g.cs", output);

                // Generate [GenerateSerializer] for each event type
                if (config.IsCloudActorsServer)
                {
                    foreach (var ev in events)
                    {
                        var evNs = ev.ContainingNamespace.IsGlobalNamespace ? "" : ev.ContainingNamespace.ToDisplayString();
                        var kind = ev.IsRecord ? "record" : "class";
                        var nsDecl = evNs.Length > 0 ? $"namespace {evNs};\n\n" : "";
                        var evOutput =
                            $$"""
                            // <auto-generated/>
                            using System.CodeDom.Compiler;
                            using Orleans;

                            {{nsDecl}}[GeneratedCode("Devlooped.CloudActors", "{{ThisAssembly.Info.InformationalVersion}}")]
                            [GenerateSerializer]
                            partial {{kind}} {{ev.Name}};
                            """;

                        var evFileName = ev.ToDisplayString(FullName).Replace('+', '.');
                        ctx.AddSource($"{evFileName}.Serializable.cs", evOutput);

                        var orleans = OrleansGenerator.GenerateCode(compilation, parseOptions as CSharpParseOptions, config, evOutput, ev.Name, ctx.CancellationToken);
                        ctx.AddSource($"{evFileName}.Serializable.orleans.cs", orleans);
                    }
                }
                else
                {
                    foreach (var ev in events)
                    {
                        var evNs = ev.ContainingNamespace.IsGlobalNamespace ? "" : ev.ContainingNamespace.ToDisplayString();
                        var kind = ev.IsRecord ? "record" : "class";
                        var nsDecl = evNs.Length > 0 ? $"namespace {evNs};\n\n" : "";
                        var evOutput =
                            $$"""
                            // <auto-generated/>
                            using System.CodeDom.Compiler;
                            using Orleans;

                            {{nsDecl}}[GeneratedCode("Devlooped.CloudActors", "{{ThisAssembly.Info.InformationalVersion}}")]
                            [GenerateSerializer]
                            partial {{kind}} {{ev.Name}};
                            """;

                        var evFileName = ev.ToDisplayString(FullName).Replace('+', '.');
                        ctx.AddSource($"{evFileName}.Serializable.cs", evOutput);
                    }
                }
            });
    }
}
