using Microsoft.CodeAnalysis;

namespace Devlooped.CloudActors;

static class SerializableGenerator
{
    public static void GenerateCode(this SourceProductionContext ctx, (INamedTypeSymbol, OrleansGeneratorOptions) source)
    {
        var (message, options) = source;

        if (options.ProduceReferenceAssembly)
            return;

        var ns = message.ContainingNamespace.ToDisplayString();
        var kind = message.IsRecord ? "record" : "class";
        var output =
            $$"""
                // <auto-generated/>

                using System.CodeDom.Compiler;
                using Orleans;

                namespace {{ns}}
                {
                    [GeneratedCode("Devlooped.CloudActors", "{{ThisAssembly.Info.InformationalVersion}}")]
                    [GenerateSerializer]
                    partial {{kind}} {{message.Name}};
                }
                """;

        ctx.AddSource($"{message.ToFileName()}.Serializable.cs", output);

        // This supports the scenario where the actor and messages exist in the server project itself, 
        // which is likely not very common but nevertheless it should be supported.
        if (options.IsCloudActorsServer)
        {
            var orleans = OrleansGenerator.GenerateCode(options, output, message.Name, ctx.CancellationToken);
            ctx.AddSource($"{message.ToFileName()}.Serializable.orleans.cs", orleans);
        }
    }
}
