using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Devlooped.CloudActors;

static class SerializableGenerator
{
    /// <summary>
    /// Generates [GenerateSerializer] code for a type, using string-only data.
    /// Compilation and ParseOptions are only used for the Orleans codegen step.
    /// </summary>
    public static void GenerateCode(this SourceProductionContext ctx, string name, string ns, string fullName, bool isRecord,
        OrleansConfig config, Compilation compilation, CSharpParseOptions? parseOptions)
    {
        if (config.ProduceReferenceAssembly)
            return;

        var kind = isRecord ? "record" : "class";
        var output =
            $$"""
                // <auto-generated/>

                using System.CodeDom.Compiler;
                using Orleans;

                namespace {{ns}}
                {
                    [GeneratedCode("Devlooped.CloudActors", "{{ThisAssembly.Info.InformationalVersion}}")]
                    [GenerateSerializer]
                    partial {{kind}} {{name}};
                }
                """;

        var fileName = fullName.Replace('+', '.');
        ctx.AddSource($"{fileName}.Serializable.cs", output);

        // This supports the scenario where the actor and messages exist in the server project itself, 
        // which is likely not very common but nevertheless it should be supported.
        if (config.IsCloudActorsServer)
        {
            var orleans = OrleansGenerator.GenerateCode(compilation, parseOptions, config, output, name, ctx.CancellationToken);
            ctx.AddSource($"{fileName}.Serializable.orleans.cs", orleans);
        }
    }
}
