using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// Analyzes referenced assemblies from current compilation and emits an attribute 
/// for each one that instructs the Orleans code generator to inspect the assembly 
/// and generate code for it: GenerateCodeForDeclaringAssembly. 
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorsAssemblyGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var config = context.GetOrleansConfig();

        // Use CompilationProvider for assembly references — extract string-only models immediately
        var assemblyModels = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var builder = ImmutableArray.CreateBuilder<CloudActorAssemblyModel>();
                foreach (var reference in compilation.GetUsedAssemblyReferences())
                {
                    if (compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol asm &&
                        asm.GetAttributes().Any(a => "Devlooped.CloudActorsAttribute".Equals(a.AttributeClass?.ToDisplayString(FullName))))
                    {
                        // Find the first accessible non-generic, non-special type from the assembly
                        var accessibleType = asm.GetAllTypes()
                            .FirstOrDefault(t =>
                                t.MetadataName != "<Module>" &&
                                t.MetadataName != "ActorBusExtensions" &&
                                t.MetadataName != "CloudActorsAttribute" &&
                                !t.MetadataName.Contains("<") &&
                                !t.IsGenericType &&
                                t.CanBeReferencedByName &&
                                t.ContainingType == null &&
                                compilation.IsSymbolAccessibleWithin(t, compilation.Assembly));

                        builder.Add(new CloudActorAssemblyModel(
                            asm.Name,
                            accessibleType?.ToDisplayString(FullName)));
                    }
                }
                return new EquatableArray<CloudActorAssemblyModel>(builder.ToImmutable());
            })
            .WithTrackingName(TrackingNames.CloudActorAssemblies);

        context.RegisterImplementationSourceOutput(
            config.Combine(assemblyModels).Combine(context.CompilationProvider).Combine(context.ParseOptionsProvider),
            (ctx, source) =>
            {
                var (((config, assemblyModels), compilation), parseOptions) = source;
                var models = assemblyModels.AsImmutableArray();
                if (models.IsDefaultOrEmpty)
                    return;

                // Don't duplicate any of the already generated code for the current assembly
                compilation = compilation.RemoveAllSyntaxTrees();

                var output = new StringBuilder().AppendLine(
                    """
                    // <auto-generated/>            
                    using Orleans;

                    """);

                foreach (var asm in models)
                {
                    output.AppendLine($"[assembly: ApplicationPartAttribute(\"{asm.AssemblyName}\")]");
                }

                foreach (var asm in models)
                {
                    if (asm.AccessibleTypeName is not null)
                        output.AppendLine($"[assembly: GenerateCodeForDeclaringAssembly(typeof({asm.AccessibleTypeName}))]");
                }

                var orleans = OrleansGenerator.GenerateCode(compilation, parseOptions as CSharpParseOptions, config, output.ToString(), "References", ctx.CancellationToken);

                ctx.AddSource($"CloudActors.cs", output.ToString());
                ctx.AddSource($"CloudActors.orleans.cs", orleans);
            });
    }
}