# Create a new account
POST http://localhost:5000/account
Content-Type: application/json

###

@id = "019a6036c5037ddcacaa29a8b75059af"

# Get the balance of the account
GET http://localhost:5000/account/{{id}}
Content-Type: application/json

###

# Deposit money (positive amount)
PUT http://localhost:5000/account/{{id}}
Content-Type: application/json

100

###

# Withdraw money (negative amount)
PUT http://localhost:5000/account/{{id}}
Content-Type: application/json

-50

###

# Close the account
DELETE http://localhost:5000/account/{{id}}
Content-Type: application/json

###