using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// Generates a compile-time <c>IActorIdFactory</c> implementation that maps actor types 
/// to their typed-ID <c>Parse</c> calls without any runtime reflection.
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorIdFactoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Use CompilationProvider to discover actors across all referenced assemblies
        var actorsWithIds = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var iParsable = compilation.GetTypeByMetadataName("System.IParsable`1");
                var builder = ImmutableArray.CreateBuilder<ActorIdEntry>();
                foreach (var type in compilation.GetAllTypes())
                {
                    if (!type.IsGenericType && type.IsActor())
                    {
                        var idInfo = GetTypedIdInfo(type, iParsable);
                        if (idInfo is not null)
                        {
                            builder.Add(new ActorIdEntry(
                                type.ToDisplayString(FullName),
                                idInfo.Value.IdTypeName));
                        }
                    }
                }
                return builder.ToImmutable();
            })
            .WithTrackingName(TrackingNames.ActorIdEntries);

        context.RegisterImplementationSourceOutput(actorsWithIds, (ctx, entries) => GenerateFactory(ctx, entries));
    }

    static void GenerateFactory(SourceProductionContext ctx, ImmutableArray<ActorIdEntry> entries)
    {
        if (entries.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine(
            """
            // <auto-generated/>
            #nullable enable
            using System;
            using System.ComponentModel;
            using System.Runtime.CompilerServices;
            using Microsoft.Extensions.DependencyInjection;
            using Devlooped.CloudActors;

            [EditorBrowsable(EditorBrowsableState.Never)]
            internal static partial class CloudActorsGeneratedExtensions
            {
                public static IServiceCollection AddCloudActors(this IServiceCollection services)
                    => services.AddCloudActors(GeneratedActorIdFactory.Instance);               
            }

            namespace Devlooped.CloudActors
            {
                file sealed class GeneratedActorIdFactory : IActorIdFactory
                {
                    public static readonly IActorIdFactory Instance = new GeneratedActorIdFactory();
            
                    public object Create(Type actorType, string key)
                    {
            """);

        foreach (var entry in entries.Distinct())
        {
            sb.AppendLine($"            if (actorType == typeof({entry.ActorTypeName}))");
            sb.AppendLine($"                return {entry.IdTypeName}.Parse(key, null);");
        }

        sb.AppendLine(
            """
                        return key;
                    }
                }
            
                file static class GeneratedActorIdFactoryModule
                {
                    [ModuleInitializer]
                    internal static void Register()
                    {
                        ActorIdFactory.Generated = GeneratedActorIdFactory.Instance;
                    }
                }
            }
            """);

        ctx.AddSource("ActorIdFactory.g.cs", sb.ToString());
    }

    static (string IdTypeName, bool IsParsable)? GetTypedIdInfo(INamedTypeSymbol actor, INamedTypeSymbol? iParsable)
    {
        var ctor = actor.Constructors
            .Where(c => !c.IsStatic && c.Parameters.Length > 0)
            .OrderBy(c => c.Parameters.Length)
            .FirstOrDefault();

        if (ctor is null)
            return null;

        var idType = ctor.Parameters[0].Type;

        if (idType.SpecialType == SpecialType.System_String)
            return null;

        // Check if idType implements IParsable<T> directly
        if (iParsable is not null)
        {
            var implementsParsable = idType.AllInterfaces.Any(i =>
                i.IsGenericType &&
                i.ConstructedFrom.Equals(iParsable, SymbolEqualityComparer.Default));

            if (implementsParsable)
                return (idType.ToDisplayString(FullName), true);
        }

        // StructId types implement IParsable<T> via a separate generator that runs
        // in parallel, so we can't see it yet. Detect IStructId by name.
        var isStructId = idType.AllInterfaces.Any(i =>
            i.ContainingNamespace?.Name == "StructId" &&
            i.Name == "IStructId");

        if (isStructId)
            return (idType.ToDisplayString(FullName), true);

        return null;
    }

    record struct ActorIdEntry(string ActorTypeName, string IdTypeName);
}
