using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using static Devlooped.CloudActors.AnalysisExtensions;

namespace Devlooped.CloudActors;

/// <summary>
/// Generates a compile-time <c>IActorIdFactory</c> implementation that maps actor types 
/// to their typed-ID <c>Parse</c> calls without any runtime reflection. Also emits an 
/// <c>AddCloudActors</c> extension method overload with 
/// <c>[OverloadResolutionPriority(1)]</c> that registers the generated factory and 
/// delegates to the library's original registration.
/// </summary>
[Generator(LanguageNames.CSharp)]
class ActorIdFactoryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var iParsable = context.CompilationProvider
            .Select((c, _) => c.GetTypeByMetadataName("System.IParsable`1"));

        var actors = context.CompilationProvider
            .SelectMany((x, _) => x.GetAllTypes())
            .Where(t => t.IsActor());

        var actorsWithIds = actors.Combine(iParsable)
            .Select((item, _) =>
            {
                var (actor, parsable) = item;
                var idInfo = GetTypedIdInfo(actor, parsable);
                if (idInfo is null)
                    return default;

                return new ActorIdEntry(
                    actor.ToDisplayString(FullName),
                    idInfo.Value.IdTypeName);
            })
            .Where(x => x.ActorTypeName is not null)
            .Collect();

        context.RegisterImplementationSourceOutput(actorsWithIds, GenerateFactory);
    }

    static void GenerateFactory(SourceProductionContext ctx, ImmutableArray<ActorIdEntry> entries)
    {
        if (entries.IsDefaultOrEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine(
            """
            // <auto-generated/>
            #nullable enable
            using System;
            using System.ComponentModel;
            using System.Runtime.CompilerServices;
            using Microsoft.Extensions.DependencyInjection;
            using Devlooped.CloudActors;

            /// <summary>Extension methods for adding Cloud Actors services to the dependency injection container.</summary>
            [EditorBrowsable(EditorBrowsableState.Never)]
            public static partial class CloudActorsGeneratedExtensions
            {
                /// <summary>Adds the <see cref="IActorBus"/> service and actor activation logic.</summary>
                public static IServiceCollection AddCloudActors(this IServiceCollection services)
                    => services.AddCloudActors(GeneratedActorIdFactory.Instance);               
            }

            namespace Devlooped.CloudActors
            {
                file sealed class GeneratedActorIdFactory : IActorIdFactory
                {
                    public static readonly IActorIdFactory Instance = new GeneratedActorIdFactory();
            
                    public object Create(Type actorType, string key)
                    {
            """);

        foreach (var entry in entries.Distinct())
        {
            sb.AppendLine($"            if (actorType == typeof({entry.ActorTypeName}))");
            sb.AppendLine($"                return {entry.IdTypeName}.Parse(key, null);");
        }

        sb.AppendLine(
            """
                        return key;
                    }
                }
            
                file static class GeneratedActorIdFactoryModule
                {
                    [ModuleInitializer]
                    internal static void Register()
                    {
                        ActorIdFactory.Generated = GeneratedActorIdFactory.Instance;
                    }
                }
            }
            """);

        ctx.AddSource("ActorIdFactory.g.cs", sb.ToString());
    }

    static (string IdTypeName, bool IsParsable)? GetTypedIdInfo(INamedTypeSymbol actor, INamedTypeSymbol? iParsable)
    {
        var ctor = actor.Constructors
            .Where(c => !c.IsStatic && c.Parameters.Length > 0)
            .OrderBy(c => c.Parameters.Length)
            .FirstOrDefault();

        if (ctor is null)
            return null;

        var idType = ctor.Parameters[0].Type;

        if (idType.SpecialType == SpecialType.System_String)
            return null;

        // Check if idType implements IParsable<T> directly
        if (iParsable is not null)
        {
            var implementsParsable = idType.AllInterfaces.Any(i =>
                i.IsGenericType &&
                i.ConstructedFrom.Equals(iParsable, SymbolEqualityComparer.Default));

            if (implementsParsable)
                return (idType.ToDisplayString(FullName), true);
        }

        // StructId types implement IParsable<T> via a separate generator that runs
        // in parallel, so we can't see it yet. Detect IStructId by name.
        var isStructId = idType.AllInterfaces.Any(i =>
            i.ContainingNamespace?.Name == "StructId" &&
            i.Name == "IStructId");

        if (isStructId)
            return (idType.ToDisplayString(FullName), true);

        return null;
    }

    record struct ActorIdEntry(string ActorTypeName, string IdTypeName);
}
