using Microsoft.CodeAnalysis;

namespace Devlooped.CloudActors;

[Generator(LanguageNames.CSharp)]
public class CloudActorsGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterImplementationSourceOutput(context.CompilationProvider, (ctx, compilation) =>
        {
            ctx.AddSource($"CloudActors.cs",
                $$"""
                // <auto-generated/>
                [assembly: Devlooped.CloudActors]

                namespace Devlooped 
                {
                    [System.AttributeUsage(System.AttributeTargets.Assembly)]
                    class CloudActorsAttribute : System.Attribute { } 
                }
                """);
        });
    }
}
